apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-demo
  template:
    spec:
      containers:
      - name: backend-demo
        imagePullPolicy: Always
        ports:
        - name: backend-demo
          containerPort: 8000
          protocol: TCP
      imagePullSecrets:
        - name: odx
---
apiVersion: v1
kind: Service
metadata:
  name: backend-demo
spec:
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-demo-ingress
spec:
  rules:
  - host: backend-demo.example.domain
    http:
      paths:
      - path:
        backend:
          serviceName: backend-demo
          servicePort: 8000
